# Generated by Django 2.2.5 on 2019-10-08 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HumiditySensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(auto_now_add=True)),
                ('parent', models.CharField(default='Adruino UNO', max_length=100)),
                ('data', models.FloatField(default=-1.0)),
                ('unit', models.CharField(default='%', max_length=10)),
                ('anamoly', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MoistureSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(auto_now_add=True)),
                ('parent', models.CharField(default='Adruino UNO', max_length=100)),
                ('data', models.FloatField(default=-1.0)),
                ('unit', models.CharField(default='%', max_length=10)),
                ('anamoly', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TempSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(auto_now_add=True)),
                ('parent', models.CharField(default='Adruino UNO', max_length=100)),
                ('data', models.FloatField(default=-1.0)),
                ('unit', models.CharField(default="'C", max_length=10)),
                ('anamoly', models.BooleanField(default=False)),
            ],
        ),
    ]
