# Generated by Django 2.2.5 on 2019-10-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation', models.BooleanField(default=False)),
                ('activationTime', models.TimeField(auto_now=True)),
                ('activationDate', models.DateField(auto_now=True)),
            ],
        ),
    ]
